# fly.toml app configuration file generated for pihole-tailscale-fly on 2024-02-25T11:19:56+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pihole-tailscale-fly'
primary_region = 'syd'

[[services]]
  protocol = 'udp'
  internal_port = 53
  ports = []

[[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '15s'

[[vm]]
  memory = '2gb'
  cpu_kind = 'performance'
  cpus = 1
